# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conversation.proto
# Protobuf Python Version: 7.34.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

_descriptor_pool_instance = _descriptor_pool.DescriptorPool()

from google.protobuf import descriptor_pb2 as _descriptor_pb2

_fd = _descriptor_pb2.FileDescriptorProto()
_fd.name = 'conversation.proto'
_fd.syntax = 'proto3'

_status = _fd.message_type.add()
_status.name = 'Status'
_f = _status.field.add(); _f.name = 'number'; _f.number = 1; _f.label = 1; _f.type = 3
_f = _status.field.add(); _f.name = 'code'; _f.number = 2; _f.label = 1; _f.type = 5
_f = _status.field.add(); _f.name = 'msg'; _f.number = 3; _f.label = 1; _f.type = 9

_cl = _fd.message_type.add()
_cl.name = 'ConversationList'

_cd = _cl.nested_type.add()
_cd.name = 'ConversationData'

_at = _cd.nested_type.add()
_at.name = 'AtData'
_f = _at.field.add(); _f.name = 'unknown'; _f.number = 1; _f.label = 1; _f.type = 3
_f = _at.field.add(); _f.name = 'mentioned_id'; _f.number = 2; _f.label = 1; _f.type = 9
_f = _at.field.add(); _f.name = 'mentioned_name'; _f.number = 3; _f.label = 1; _f.type = 9
_f = _at.field.add(); _f.name = 'mentioned_in'; _f.number = 4; _f.label = 1; _f.type = 9
_f = _at.field.add(); _f.name = 'mentioner_id'; _f.number = 6; _f.label = 1; _f.type = 9
_f = _at.field.add(); _f.name = 'mentioner_name'; _f.number = 7; _f.label = 1; _f.type = 9
_f = _at.field.add(); _f.name = 'msg_seq'; _f.number = 8; _f.label = 1; _f.type = 3

_f = _cd.field.add(); _f.name = 'chat_id'; _f.number = 1; _f.label = 1; _f.type = 9
_f = _cd.field.add(); _f.name = 'chat_type'; _f.number = 2; _f.label = 1; _f.type = 5
_f = _cd.field.add(); _f.name = 'name'; _f.number = 3; _f.label = 1; _f.type = 9
_f = _cd.field.add(); _f.name = 'chat_content'; _f.number = 4; _f.label = 1; _f.type = 9
_f = _cd.field.add(); _f.name = 'timestamp_ms'; _f.number = 5; _f.label = 1; _f.type = 3
_f = _cd.field.add(); _f.name = 'unread_message'; _f.number = 6; _f.label = 1; _f.type = 5
_f = _cd.field.add(); _f.name = 'at'; _f.number = 7; _f.label = 1; _f.type = 5
_f = _cd.field.add(); _f.name = 'avatar_id'; _f.number = 8; _f.label = 1; _f.type = 3
_f = _cd.field.add(); _f.name = 'avatar_url'; _f.number = 9; _f.label = 1; _f.type = 9
_f = _cd.field.add(); _f.name = 'do_not_disturb'; _f.number = 11; _f.label = 1; _f.type = 5
_f = _cd.field.add(); _f.name = 'timestamp'; _f.number = 12; _f.label = 1; _f.type = 3
_f = _cd.field.add(); _f.name = 'at_data'; _f.number = 14; _f.label = 1; _f.type = 11; _f.type_name = '.ConversationList.ConversationData.AtData'
_f = _cd.field.add(); _f.name = 'certification_level'; _f.number = 16; _f.label = 1; _f.type = 5

_f = _cl.field.add(); _f.name = 'status'; _f.number = 1; _f.label = 1; _f.type = 11; _f.type_name = '.Status'
_f = _cl.field.add(); _f.name = 'data'; _f.number = 2; _f.label = 3; _f.type = 11; _f.type_name = '.ConversationList.ConversationData'
_f = _cl.field.add(); _f.name = 'total'; _f.number = 3; _f.label = 1; _f.type = 5
_f = _cl.field.add(); _f.name = 'request_id'; _f.number = 4; _f.label = 1; _f.type = 9

DESCRIPTOR = _descriptor_pool_instance.Add(_fd)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conversation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=22
  _globals['_STATUS']._serialized_end=73
  _globals['_CONVERSATIONLIST']._serialized_start=76
  _globals['_CONVERSATIONLIST']._serialized_end=685
  _globals['_CONVERSATIONLIST_CONVERSATIONDATA']._serialized_start=207
  _globals['_CONVERSATIONLIST_CONVERSATIONDATA']._serialized_end=685
  _globals['_CONVERSATIONLIST_CONVERSATIONDATA_ATDATA']._serialized_start=529
  _globals['_CONVERSATIONLIST_CONVERSATIONDATA_ATDATA']._serialized_end=685
# @@protoc_insertion_point(module_scope)
