# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: friend.proto
# Protobuf Python Version: 7.34.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '-rc1',
    'friend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66riend.proto\"3\n\x06Status\x12\x0e\n\x06number\x18\x01 \x01(\x03\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\"\xf9\x03\n\x0crequest_list\x12\x17\n\x06status\x18\x01 \x01(\x0b\x32\x07.Status\x12\'\n\x08requests\x18\x02 \x03(\x0b\x32\x15.request_list.Request\x12\r\n\x05total\x18\x03 \x01(\x05\x12\x0f\n\x07pending\x18\x04 \x01(\x05\x1a\x86\x03\n\x07Request\x12\x14\n\x0creceiverName\x18\x01 \x01(\t\x12\x16\n\x0ereceiverAvatar\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t\x12\x11\n\tgroupName\x18\x05 \x01(\t\x12\x13\n\x0bgroupAvatar\x18\x06 \x01(\t\x12\x11\n\tinviterId\x18\x07 \x01(\t\x12\x12\n\nsourceType\x18\t \x01(\x05\x12\x12\n\ntargetType\x18\n \x01(\x05\x12\x10\n\x08targetId\x18\x0b \x01(\t\x12\x12\n\nreceiverId\x18\x0c \x01(\t\x12\x0e\n\x06result\x18\r \x01(\x05\x12\x13\n\x0bprocessedAt\x18\x0e \x01(\x03\x12\x10\n\x08inviteAt\x18\x10 \x01(\x03\x12\x13\n\x0binviteAtStr\x18\x11 \x01(\t\x12\x11\n\trequestId\x18\x12 \x01(\x05\x12\x0f\n\x07\x62otName\x18\x13 \x01(\t\x12\x11\n\tbotAvatar\x18\x14 \x01(\t\x12\x15\n\rprocessorName\x18\x16 \x01(\t\x12\x0c\n\x04note\x18\x17 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'friend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=16
  _globals['_STATUS']._serialized_end=67
  _globals['_REQUEST_LIST']._serialized_start=70
  _globals['_REQUEST_LIST']._serialized_end=575
  _globals['_REQUEST_LIST_REQUEST']._serialized_start=185
  _globals['_REQUEST_LIST_REQUEST']._serialized_end=575
# @@protoc_insertion_point(module_scope)
