# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: instruction.proto
# Protobuf Python Version: 7.34.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '-rc1',
    'instruction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11instruction.proto\"!\n\x13get_bot_instruction\x12\n\n\x02id\x18\x03 \x01(\t\"3\n\x06Status\x12\x0e\n\x06number\x18\x01 \x01(\x04\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x04\x12\x0b\n\x03msg\x18\x03 \x01(\t\"\xdf\x01\n\x10instruction_list\x12\x17\n\x06status\x18\x01 \x01(\x0b\x32\x07.Status\x12$\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x16.instruction_list.Data\x1a\x8b\x01\n\x04\x44\x61ta\x12\x12\n\ncommand_id\x18\x01 \x01(\x04\x12\x0e\n\x06\x62ot_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63ommand_name\x18\x03 \x01(\t\x12\x18\n\x10instruction_type\x18\x05 \x01(\x04\x12\x14\n\x0c\x64\x65\x66\x61ult_text\x18\x07 \x01(\t\x12\x19\n\x11\x62ot_settings_json\x18\n \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'instruction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GET_BOT_INSTRUCTION']._serialized_start=21
  _globals['_GET_BOT_INSTRUCTION']._serialized_end=54
  _globals['_STATUS']._serialized_start=56
  _globals['_STATUS']._serialized_end=107
  _globals['_INSTRUCTION_LIST']._serialized_start=110
  _globals['_INSTRUCTION_LIST']._serialized_end=333
  _globals['_INSTRUCTION_LIST_DATA']._serialized_start=194
  _globals['_INSTRUCTION_LIST_DATA']._serialized_end=333
# @@protoc_insertion_point(module_scope)
