# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msg.proto
# Protobuf Python Version: 7.34.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

_descriptor_pool_instance = _descriptor_pool.DescriptorPool()
from google.protobuf import descriptor_pb2 as _descriptor_pb2

_fd = _descriptor_pb2.FileDescriptorProto()
_fd.name = 'msg.proto'
_fd.syntax = 'proto3'

_status = _fd.message_type.add()
_status.name = 'Status'
_f = _status.field.add(); _f.name = 'number'; _f.number = 1; _f.label = 1; _f.type = 3
_f = _status.field.add(); _f.name = 'code'; _f.number = 2; _f.label = 1; _f.type = 5
_f = _status.field.add(); _f.name = 'msg'; _f.number = 3; _f.label = 1; _f.type = 9

_tag = _fd.message_type.add()
_tag.name = 'Tag'
_f = _tag.field.add(); _f.name = 'id'; _f.number = 1; _f.label = 1; _f.type = 3
_f = _tag.field.add(); _f.name = 'text'; _f.number = 3; _f.label = 1; _f.type = 9
_f = _tag.field.add(); _f.name = 'color'; _f.number = 4; _f.label = 1; _f.type = 9

_msg = _fd.message_type.add()
_msg.name = 'Msg'

_sender = _msg.nested_type.add()
_sender.name = 'Sender'
_f = _sender.field.add(); _f.name = 'chat_id'; _f.number = 1; _f.label = 1; _f.type = 9
_f = _sender.field.add(); _f.name = 'chat_type'; _f.number = 2; _f.label = 1; _f.type = 4
_f = _sender.field.add(); _f.name = 'name'; _f.number = 3; _f.label = 1; _f.type = 9
_f = _sender.field.add(); _f.name = 'avatar_url'; _f.number = 4; _f.label = 1; _f.type = 9
_f = _sender.field.add(); _f.name = 'tag_old'; _f.number = 6; _f.label = 3; _f.type = 9
_f = _sender.field.add(); _f.name = 'tag'; _f.number = 7; _f.label = 3; _f.type = 11; _f.type_name = '.Tag'

_cmd = _msg.nested_type.add()
_cmd.name = 'Cmd'
_f = _cmd.field.add(); _f.name = 'name'; _f.number = 2; _f.label = 1; _f.type = 9
_f = _cmd.field.add(); _f.name = 'type'; _f.number = 4; _f.label = 1; _f.type = 4

_content = _msg.nested_type.add()
_content.name = 'Content'
_f = _content.field.add(); _f.name = 'text'; _f.number = 1; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'buttons'; _f.number = 2; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'image_url'; _f.number = 3; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'file_name'; _f.number = 4; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'file_url'; _f.number = 5; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'form'; _f.number = 7; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'quote_msg_text'; _f.number = 8; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'sticker_url'; _f.number = 9; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'post_id'; _f.number = 10; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'post_title'; _f.number = 11; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'post_content'; _f.number = 12; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'post_content_type'; _f.number = 13; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'expression_id'; _f.number = 15; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'quote_image_url'; _f.number = 16; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'quote_image_name'; _f.number = 17; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'file_size'; _f.number = 18; _f.label = 1; _f.type = 4
_f = _content.field.add(); _f.name = 'video_url'; _f.number = 19; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'audio_url'; _f.number = 21; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'audio_time'; _f.number = 22; _f.label = 1; _f.type = 4
_f = _content.field.add(); _f.name = 'quote_video_url'; _f.number = 23; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'quote_video_time'; _f.number = 24; _f.label = 1; _f.type = 4
_f = _content.field.add(); _f.name = 'sticker_item_id'; _f.number = 25; _f.label = 1; _f.type = 4
_f = _content.field.add(); _f.name = 'sticker_pack_id'; _f.number = 26; _f.label = 1; _f.type = 4
_f = _content.field.add(); _f.name = 'call_text'; _f.number = 29; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'call_status_text'; _f.number = 32; _f.label = 1; _f.type = 9
_f = _content.field.add(); _f.name = 'width'; _f.number = 33; _f.label = 1; _f.type = 4
_f = _content.field.add(); _f.name = 'height'; _f.number = 34; _f.label = 1; _f.type = 4
_f = _content.field.add(); _f.name = 'tip'; _f.number = 37; _f.label = 1; _f.type = 9

_f = _msg.field.add(); _f.name = 'msg_id'; _f.number = 1; _f.label = 1; _f.type = 9
_f = _msg.field.add(); _f.name = 'sender'; _f.number = 2; _f.label = 1; _f.type = 11; _f.type_name = '.Msg.Sender'
_f = _msg.field.add(); _f.name = 'direction'; _f.number = 3; _f.label = 1; _f.type = 9
_f = _msg.field.add(); _f.name = 'content_type'; _f.number = 4; _f.label = 1; _f.type = 4
_f = _msg.field.add(); _f.name = 'content'; _f.number = 5; _f.label = 1; _f.type = 11; _f.type_name = '.Msg.Content'
_f = _msg.field.add(); _f.name = 'send_time'; _f.number = 6; _f.label = 1; _f.type = 4
_f = _msg.field.add(); _f.name = 'cmd'; _f.number = 7; _f.label = 1; _f.type = 11; _f.type_name = '.Msg.Cmd'
_f = _msg.field.add(); _f.name = 'msg_delete_time'; _f.number = 8; _f.label = 1; _f.type = 4
_f = _msg.field.add(); _f.name = 'quote_msg_id'; _f.number = 9; _f.label = 1; _f.type = 9
_f = _msg.field.add(); _f.name = 'msg_seq'; _f.number = 10; _f.label = 1; _f.type = 4
_f = _msg.field.add(); _f.name = 'edit_time'; _f.number = 12; _f.label = 1; _f.type = 4

_lms = _fd.message_type.add()
_lms.name = 'list_message_send'
_f = _lms.field.add(); _f.name = 'msg_count'; _f.number = 2; _f.label = 1; _f.type = 4
_f = _lms.field.add(); _f.name = 'msg_id'; _f.number = 3; _f.label = 1; _f.type = 9
_f = _lms.field.add(); _f.name = 'chat_type'; _f.number = 4; _f.label = 1; _f.type = 4
_f = _lms.field.add(); _f.name = 'chat_id'; _f.number = 5; _f.label = 1; _f.type = 9

_lm = _fd.message_type.add()
_lm.name = 'list_message'
_f = _lm.field.add(); _f.name = 'status'; _f.number = 1; _f.label = 1; _f.type = 11; _f.type_name = '.Status'
_f = _lm.field.add(); _f.name = 'msg'; _f.number = 2; _f.label = 3; _f.type = 11; _f.type_name = '.Msg'

_sms = _fd.message_type.add()
_sms.name = 'send_message_send'

_sms_data = _sms.nested_type.add()
_sms_data.name = 'Data'
_f = _sms_data.field.add(); _f.name = 'text'; _f.number = 1; _f.label = 1; _f.type = 9
_f = _sms_data.field.add(); _f.name = 'image'; _f.number = 9; _f.label = 1; _f.type = 9

_sms_media = _sms.nested_type.add()
_sms_media.name = 'Media'
_f = _sms_media.field.add(); _f.name = 'file_key'; _f.number = 1; _f.label = 1; _f.type = 9
_f = _sms_media.field.add(); _f.name = 'file_hash'; _f.number = 2; _f.label = 1; _f.type = 9
_f = _sms_media.field.add(); _f.name = 'file_type'; _f.number = 3; _f.label = 1; _f.type = 9
_f = _sms_media.field.add(); _f.name = 'image_height'; _f.number = 5; _f.label = 1; _f.type = 3
_f = _sms_media.field.add(); _f.name = 'image_width'; _f.number = 6; _f.label = 1; _f.type = 3
_f = _sms_media.field.add(); _f.name = 'file_size'; _f.number = 7; _f.label = 1; _f.type = 3
_f = _sms_media.field.add(); _f.name = 'file_key2'; _f.number = 8; _f.label = 1; _f.type = 9
_f = _sms_media.field.add(); _f.name = 'file_suffix'; _f.number = 9; _f.label = 1; _f.type = 9

_f = _sms.field.add(); _f.name = 'msg_id'; _f.number = 2; _f.label = 1; _f.type = 9
_f = _sms.field.add(); _f.name = 'chat_id'; _f.number = 3; _f.label = 1; _f.type = 9
_f = _sms.field.add(); _f.name = 'chat_type'; _f.number = 4; _f.label = 1; _f.type = 4
_f = _sms.field.add(); _f.name = 'data'; _f.number = 5; _f.label = 1; _f.type = 11; _f.type_name = '.send_message_send.Data'
_f = _sms.field.add(); _f.name = 'content_type'; _f.number = 6; _f.label = 1; _f.type = 4
_f = _sms.field.add(); _f.name = 'media'; _f.number = 9; _f.label = 1; _f.type = 11; _f.type_name = '.send_message_send.Media'

_sm = _fd.message_type.add()
_sm.name = 'send_message'
_f = _sm.field.add(); _f.name = 'status'; _f.number = 1; _f.label = 1; _f.type = 11; _f.type_name = '.Status'

DESCRIPTOR = _descriptor_pool_instance.Add(_fd)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_pb2', _globals)
